### ISSUE TITLE
JS tracking and AMP compatibility

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/statify#110]
I stumbled upon this blog post about making Statify AMP compatible:
https://die-computermaler.de/statify-und-amp-accelerated-mobile-pages/

> Eigener JavaScript-Code kann in AMP-Seiten spezifikationsbedingt nur mit erheblichen Verrenkungen ausgeführt werden und wird vom „Sanitizer“ des WordPress-AMP-Plugins (<https://de.wordpress.org/plugins/amp/>) dementsprechend sinnvollerweise herausgefiltert. Das Ärgerliche daran ist: Sowohl die mobile Suche von Google als auch die mobilen Twitter-Apps verweisen i. d. R. auf die AMP-Version der Seite – mobile Aufrufe von Twitter-App-Nutzern oder Aufrufe über die mobile Google-Suche bleiben also für Statify größtenteils unsichtbar.

> Glücklicherweise ist dieses Problem lösbar: Die AMP-Spezifikation verfügt über das Tag <amp-analytics>, dem per JSON-„Script“ Anweisungen übergeben werden können, welche URL bei welchem Event zu Tracking-Zwecken aufgerufen werden soll. Das WordPress-AMP-Plugin verfügt zudem unter „AMP“ → „Analytics“ über eine eigene Konfigurationsseite für eben diese JSON-Datei. Hinterlegt man dort eine entsprechende Konfiguration, kann man bei jedem Aufruf einer AMP-Seite die selbe Tracking-URL ansprechen lassen, der für „normale“ Seiten vom Statify-Tracking-Script aufgerufen wird:

So we could try to do this programmatically (automatic or per option) or we can add this to our documentation.

**Comment by felixarntz** [comment]
I haven't looked at this any closer so far than reading the documentation in https://github.com/ampproject/docs/blob/master/content/docs/analytics/analytics-vendors.md, so I can't really be of any help here unfortunately. This generally is the right approach, of course I'm not aware about the specific details that Statify would require. However the article seems to give a good headstart.

Regarding the implementation, it would probably be best if Statify supported this out-of-the-box, without requiring manual addition of the complicated information via the AMP plugin. The plugin might as well check `if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() )` and then output the necessary AMP-HTML with the JSON data automatically (instead of the default script it outputs). That would be more comfortable for the users. I consider the current textarea that the AMP plugin provides just a non-user-friendly fallback solution for Analytics providers and plugins that don't support it themselves.

**Comment by Zodiac1978** [comment]
@felixarntz Thanks for your feedback! :)

**Comment by patrickrobrecht** [comment]
Implemented in #116, bugfixed in #182.
