### ISSUE TITLE
Using statify with headless wordpress

### ISSUE THREAD

**Issue by tmo207** [pluginkollektiv/statify#130]
Hey, I built a website with gatsby.js and wordpress as the headless CMS. My client had Statify running on there old site. Now the folder structure changed (wordpress is lying in a subdirectory now and my static html files are in the root) and wordpress is only used for my backend, so of course statify doesn't count the visitors anymore. Is there are way to get it back running?
In other words: what file/function do I have to call to initalize a statify session via htaaccess or my javascript code?
Thanks for your help.

**Comment by stklcode** [comment]
If you enable tracking via JavaScript (which is designed for compatibility with cached sites), you might include our JS snippet in your custom code:
https://github.com/pluginkollektiv/statify/blob/7f635519532e4e5b4348c751f7c26f282a0f485a/js/snippet.js

If you choose to include the script, you might need to add an element with the base URL:
```html
<div id="statify-js-snippet" style="display:none"
     data-home-url="/path/to/wordpress/"></div>
<!-- [...] -->
<script src="/path/to/wordpress/wp-content/plugins/statify/js/snippet.js"></script>
```

Otherwise just build the GET request yourself. Point it to your WP root and add the two parameters `statify_referrer` and `statify_target`. Target path should be a relative URL and/or must pass [wp_validate_redirect()](https://developer.wordpress.org/reference/functions/wp_validate_redirect/)

If your WP root is not reachable for the client, you might proxy the request through a custom endpoint as well.

Note the AJAX behavior might change in 1.7 if we merge #109.

**Comment by tmo207** [comment]
Thanks for the quick answer @stklcode. I did as you proposed and included your snippet in my code. I now see a 204 request response with the parameters, but in statify on my wp dashboard I can still only see the old page visits, the new ones don't appear. Tracking via javascript is enabled, too. Anything else I have to take care of?


<img width="983" alt="Screenshot 2019-09-04 at 18 21 43" src="https://user-images.githubusercontent.com/29772543/64273212-23165200-cf41-11e9-8854-7b7ef2981925.png">

**Comment by stklcode** [comment]
204 exactly what statify responds if the JS hook is triggerd. So chances are high that you're actually talking to the plugin.

Did you force the transient dashboard data to refresh? Open the config panel and click "Save" (no need to change anything) will flush the cache immediately.

If there is still no data, most likely one of the filters triggered. User agent is OK and I assume you are not logged in, right?
You might try disabling the `skip_tracking` filters with a custom hook like this (not necessarily recommended for production use, but might give a hint where to search for the problem):
```php
add_filter( 'statify__skip_tracking', function() { return false; } );
```

**Comment by tmo207** [comment]
I reinstalled the plugin which didn't solve it. So I digged into the database and realised that the wp_statify table exists, but no values get written into it. I don't get yet how the connection between the network request and the write to database is supposed to work. As far as I understand the Statify_Frontend class usally takes care of it, but I'm not sure how to pass request values and call the class from my static site. Or is there another way which I'm overseeing here?

Maybe important to mention: the Statify_Frontend class is not called at all. Due to Gatsby.js I'm only communicating with the Wordpress REST API. So I don't have any PHP in my template.

**Comment by stklcode** [comment]
I just tried myself on a test site with a debugger attached.

Wordpress (5.2.4-alpha, Statify 1.6.3) is hosted under `/wordpress/` and my `/test.html` features a static HTML page with no relation to WordPress at all.
```html
<!DOCTYPE html>
<html><body>
  <p>This is a Statify test...</p>
  <div id="statify-js-snippet" style="display:none" data-home-url="/wordpress/"></div>
  <script src="/wordpress/wp-content/plugins/statify/js/snippet.js"></script>
</body></html>
```

Opening the `/test.html` triggers a request as in your screenshot above with a 204 response.
My `wp_statify` table contains a new column
```
+------------+----------+------------+
| created    | referrer | target     |
+------------+----------+------------+
| 2019-09-06 |          | /test.html |
```

----

> Maybe important to mention: the Statify_Frontend class is not called at all. [...]

It should be called. The `template_redirect` hook triggers `Statify_Frontend::track_visit()`. By calling the WP home page via the JavaScript snippet shis should be the path.

> As far as I understand the Statify_Frontend class usally takes care of it, but I'm not sure how to pass request values and call the class from my static site.

The plugin relies on presence of certain WP specific globals and functions, so simply calling the `Statify_Frontend::track_visit()` from any custom logic will not lead to any valid result (would be faster to write it from scratch with vanilla PHP than trying to rebuild the WP environment),

A pure JS solution calling WordPress for you, as with the example above, is the only feasible way in my eyes.

**Comment by tmo207** [comment]
I now tried to do the same thing: setting up a clean wordpress install, adding an index file which calls my snippet, etc. But unfortunately it still doesn't work. It gets the 204 response, but no entry in my database. If you are interested in why this is happening, I sent you an email with the test page so you can check it out.

**Comment by stklcode** [comment]
We finally solved the issue.

**Cause:**
Site and home URLs have been overwritten in the _config.php_:
```php
define( 'WP_SITEURL', 'https://example.com/wordpress' );
define( 'WP_HOME',    'https://example.com' );
```

The request from the _Statify_ JS snippet calls `https://example.com/wordpress/`. Unfortunately WP returns _404_ in this case.

**Solution**:
Changing the defined URLs is no option in this case. Thus the request URI must either be rewritten to the site's root `/` while internally forwarding to `/wordpress/index.php`. This either re-enables the actual WordPress site or the server config gets kinda unhandy.

Overriding the 404 status in the `statify__skip_tracking` hook seems legit here. The JS integration must take care of not tracking 404s anyway. And because we only manipulate the flag if Statify is called (which returns a 204 in either case), we do not mess up WP too much and preverse the rest of the filter chain.

```php
add_filter(
   'statify__skip_tracking',
   function () {
      global $wp_query;
      if ( isset( $wp_query ) ) {
         $wp_query->is_404 = false;
      }
      return null;
   }
);
```
