### ISSUE TITLE
Invalid markup by AMP plugin with enabled JavaScript tracking

### ISSUE THREAD

**Issue by MatzeKitt** [pluginkollektiv/statify#181]
Every time I save a post I get two validation errors in the [official AMP plugin](https://wordpress.org/plugins/amp/) with enabled JavaScript tracking:

> Invalid inline script
> Fehlercode
> DISALLOWED_TAG
> Ungültiges Markup
> <script … >
> Element-Attribute
> type	text/javascript
> id	statify-js-js-extra
> Element-Name
> script
> Übergeordnetes Element
> body
> Textinhalt
>  128 Bytes
> /* <![CDATA[ */
> var statify_ajax = {"url":"https:\/\/kittmedia.com\/wp-admin\/admin-ajax.php","nonce":"3d82495992"};
> /* ]]> */

> Invalid script snippet.min.js
> Fehlercode
> DISALLOWED_TAG
> Ungültiges Markup
> <script … >
> Element-Attribute
> type	text/javascript
> src	https://kittmedia.com/wp-content/plugins/statify/js/snippet.min.js
> id	statify-js-js
> Element-Name
> script
> Übergeordnetes Element
> body

Due to the fact that Statify is recommending using the JavaScript tracking method to track AMP pages as well, I would assume that it will work properly. However, as soon as this invalid markup gets removed (which is required in order to serve AMP pages), Statify isn’t able anymore to track any AMP page visits.

AMP version: 2.0.0 (already occurred in version 1.5.x)
Statify version: 1.8.0
WordPress version: 5.5.0

**Comment by Zodiac1978** [comment]
Related #110 and #116

**Comment by stklcode** [comment]
That's right, we always include the JS, if JS-Tracking is enabled:

https://github.com/pluginkollektiv/statify/blob/a775618721a5ec8d93f403805c5c138cce201f95/inc/class-statify-frontend.php#L387-L403

> Statify isn’t able anymore to track any AMP page visits.

Are you sure it isn't?

We do have the `amp_post_template_analytics()` method to register a separate analysis hook:
https://github.com/pluginkollektiv/statify/blob/a775618721a5ec8d93f403805c5c138cce201f95/inc/class-statify-frontend.php#L413

The script tag is removed from AMP markup, but that should be OK here. Otherwise we would track twice.
So if visits are not tracked, it's not because the script is removed, but likely for a different reason.

Nevertheless we should not include it at all, if we are processing an AMP request to remove the unnecessary warning.

**Comment by MatzeKitt** [comment]
> Are you sure it isn’t?

Yes, I am.

Visiting https://kittmedia.com as guest adds an entry in the database table of Statify, visiting https://kittmedia.com/?amp does not.

**Comment by stklcode** [comment]
OK, I got the point. In fact we got 2 problems here:

1. the invalid markup due to the unnecessary `<script>` tags
  => Simple solution, don't add the snippet on AMP requests
2. We use the `amp_post_template_analytics` hook, which is only available in _Reader Mode_
  => Additionally hook into `amp_analytics_entries` for Standard/transitional Mode (cave: different data model)
