### ISSUE TITLE
Javascript inclusion when bot visits.

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/statify#84]
Javascript is not included in a cached page, when a bot was the first visitor.

As far as I can see, the problem is the interplay between those two areas:

https://github.com/pluginkollektiv/statify/blob/master/inc/statify_frontend.class.php#L268-L270

https://github.com/pluginkollektiv/statify/blob/master/inc/statify_frontend.class.php#L141-L145

**Comment by patrickrobrecht** [comment]
At first view it looks like removing https://github.com/pluginkollektiv/statify/blob/master/inc/statify_frontend.class.php#L268-L270 would fix the problem, right?

**Comment by websupporter** [comment]
Yes, I think so @patrickrobrecht 
If I see it correctly, in `track_visit()` we check again, if we want to skip, so I think it is quite safe to remove this check in the `wp_footer()`

**Comment by patrickrobrecht** [comment]
Unfortunately removing https://github.com/pluginkollektiv/statify/blob/master/inc/statify_frontend.class.php#L268-L270 is not the correct solution. After removing this, JS tracking will log 404 errors for example (because `is_404()` is not true for the XMLHttpRequest such that tracking is not skipped).
