### ISSUE TITLE
check_referrer() excluded too many visitors

### ISSUE THREAD

**Issue by stklcode** [pluginkollektiv/statify#93]
I got some issues with the `Statify_Frontend::check_referrer()` method.

1. The method returns `true` if the HTTP referrer is empty and thus excludes the current visitor from tracking. That cannot be intentional or did I miss a point here?
2. The filter checks the actual HTTP referrer, which is often (if not always) empty, if JS tracking is enabled.

From my point of view (I don't have this option enabled on any real-world site) both can be considered as bugs.

**Comment by bueltge** [comment]
I mean you have right and an empty referrer is in this context not true, so that we should change this and declare as bug.

Check is here: https://github.com/pluginkollektiv/statify/blob/cc0f1684d402866bcb583cda0df4be97344f7b8d/inc/class-statify-frontend.php#L203-L205

In this context we should also change the if/else check to set `''` for the referrer. The else is not necessary and a solid define of the var before is in my mind much better.
https://github.com/pluginkollektiv/statify/blob/cc0f1684d402866bcb583cda0df4be97344f7b8d/inc/class-statify-frontend.php#L196-L201

**Comment by stklcode** [comment]
Added a PR for the first part, including your suggested cleanup. It is not necessary to sanitize `null`/`false` in any way and even the `empty( $referrer )` block can be removed completely.

Still not 100% sure what to do with part 2... Is this intentional or did we just forget about JS here?

If the latter is the case, I'd pass the previously determined referrer string through the methods and check against this to not duplicate the entire `if ( $is_snippet ) ... ` block.

**Comment by bueltge** [comment]
@stklcode Thanks for the issue and PR, can you add a hint in the changelog for the next release?

also a small hint, please update the version tag of the function in 
https://github.com/pluginkollektiv/statify/blob/master/inc/class-statify-frontend.php#L194

**Comment by bueltge** [comment]
Thanks a lot! @stklcode

**Comment by bueltge** [comment]
The release is also done: https://github.com/pluginkollektiv/statify/releases/tag/1.6.3

**Comment by bueltge** [comment]
Also now it is live via SVN on https://wordpress.org/plugins/statify/
